- hosts: dev
  remote_user: lok
  become: true

  vars:
    project_root: /var/www/html

  tasks: 
  - name: stopped apache service
    service: name=httpd enabled=no

  - name: Place the index file at project root
    copy: src=index.html dest={{ project_root }}/index.html owner=apache group=apache mode=0644

  - name: Enable Apache on system reboot
    service: name=httpd enabled=yes
    notify: restart apache

  handlers:
  - name: restart apache
    service: name=httpd state=restarted
